config/routes.rb
Rails.application.routes.draw do
  get 'users/profile'
  #get 'users/show'
  #get 'users/:id/edit' => 'users#edit', as: 'edit_user'
  #patch 'users/:id' => 'users#update', as: 'update_user'
  get 'home/index'
  post 'animals' => 'animals#create'
  get 'animals' => 'animals#index'
  patch 'animals/:id' => 'animals#update', as: 'update_animal'
  root to: 'animals#index'
  get '/users/:id/following' => 'users#follow', as:'follow'
  get '/users/:id/followers' => 'users#follower', as:'follower'
  get '/users/show_follow' => 'users#show_follow'
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :animals, only: [:new, :create, :index, :show, :edit]

  resources :relationships, only: [:create, :destroy]
  post "posts/creat" => "posts#creat"

  get 'like/:id' => 'likes#create', as: 'create_like_get'
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
end

app/models/animal.rb
class Animal < ApplicationRecord
	belongs_to :user
	attachment :image
	validates :animal_name, presence: true
	has_many :likes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :animal
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user

	has_many :likes
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  has_many :posts

  has_many :animals, dependent: :destroy

  has_many :likes

  attachment :profile_image
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable#, :validatable

         def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

  def liked_by?(animal_id)
    likes.where(animal_id: animal_id).exists?
  end

  end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  def index
    @animals = Animal.all
    @user = current_user
  end

  def show
    @animal = Animal.find(params[:id])
    #@animal = Animal.find_by(id: params[:id])
    @user = User.find_by(id: @animal.user_id)
    @animals = @user.animals
    #@newanimal = Animal.new
    #@comment = Comment.new
    #@comments = @animal.comments
  end

  def new
    @animal = Animal.new
  end

  def create
    @animal = Animal.new(animal_params)
    @animal.user_id = current_user.id
    if @animal.save
    redirect_to animals_path
    else
      render :new
    end
  end

  def edit
    @animal = Animal.find(params[:id])
    @animals = Animal.all
  end

  def destroy
    @animal = Animal.find(params[:id])
      @animal.destroy
      redirect_to animals_path
  end

  def update
    @animal = Animal.find(params[:id])
    if @animal.update(animal_params)
    redirect_to animal_path(@animal.id),notice: "アップデートに成功しました！"
    else
      render :edit
    end
  end
private
  def animal_params
    params.require(:animal).permit(:animal_name, :image, :caption)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
	before_action :configure_permitted_parameters, if: :devise_controller?
	protect_from_forgery with: :exception

	protected

	def configure_permitted_parameters
		added_attrs = [ :email, :name, :profile_image, :profile_image_id, :password, :password_confirmation ]
		devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
		devise_parameter_sanitizer.permit :account_update, keys: added_attrs
		#devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :post_params

  def create
    @like = Like.create(user_id: current_user.id, animal_id: params[:id])
  end

  def destroy
    @like = Like.find_by(user_id: current_user.id, animal_id: params[:id]).destroy
  end

private

  def post_params
    @animal = Animal.find(params[:id])
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :set_user

  def create
    following = current_user.follow(@user)
    if following.save
      flash[:success] = 'ユーザーをフォローしました'
      #redirect_to @user
      redirect_to request.referrer
    else
      flash.now[:alert] = 'ユーザーのフォローに失敗しました'
      #redirect_to @user
      redirect_to request.referrer
    end
  end

  def destroy
    following = current_user.unfollow(@user)
    if following.destroy
      flash[:success] = 'ユーザーのフォローを解除しました'
      redirect_to request.referrer
    else
      flash.now[:alert] = 'ユーザーのフォロー解除に失敗しました'
      redirect_to request.referrer
    end
  end

  private
  def set_user
    @user = User.find(params[:follow_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @newAnimal = Animal.new
    @animals = @user.animals
  end

  def edit
  	@user = User.find(params[:id])
  end

  def destroy
    @animal = Animal.find(params[:id])
    @animal.destroy
    redirect_to animals_path
  end

  def update
    @user = User.find(params[:id])

    #binding.pry
    if @user.update(user_params)
      flash[:notice]="You have updated user successfully."
      redirect_to user_path(@user.id), notice: "ユーザー情報を更新しました。"
    else
    render :edit
    end
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.followings
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  def show_follow
    @users = User.all
    @user = current_user
    @newAnimal = Animal.new
    @animals = @user.animals
      #@animals = Animal.all
  end

private
  def user_params
    params.require(:user).permit(:name, :profile_image)
  end

end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/animals/edit.html.erb
<div class="container">
    <div class="col-mx-3">
      <%= render "users/profile", user: @user %>
    </div>
<% if @animal.errors.any? %>
    <%= @animal.errors.count %>件のエラーが発生しました
    <% @animal.errors.full_messages.each do |message| %>
      <%= message %>
   <% end %> 
   <% end %> 
<div class="left">
  <h1>投稿編集</h1>

  <%= form_for(@animal) do |f| %>
 
  <h4>タイトル</h4>
  <%= f.text_field :animal_name %>
 
  <h4>説明</h4>
  <%= f.text_area :caption %>
  <h4></h4>
  <%= f.submit 'アップデート' %>
  <%= link_to '詳細',animal_path %>
  <h4></h4>
  <%= link_to :back do %>
  <button>戻る</button>
  <% end %>
<% end %>
</div>

app/views/animals/index.html.erb
<div class="container">
<div class="row">
		<div class="col-md-3">
			<%= render "users/profile", user: @user %>
		</div>

		<div class="col-md-9">
			<div class='animal'></div>
				<div class="row">
					<% @animals.each do |animal| %>
						<div class="col-md-4">
							<div class="container">
							    <div class="row">
							      <div class="col-lg-4">
									<div class="card" style="width: 14rem;">
										<%= attachment_image_tag animal.user, :profile_image, size: "30x30", fallback: "no_image.jpg" %>
										<h4 class="card-title"><%= animal.user.name %></h4>
										<%= attachment_image_tag animal, :image, :fill, 150, 150, format: 'jpeg', class: "card-img-top" %>
									  <div class="card-body">
									    <h4 class="card-title"><%= animal.animal_name %></h4>
									    <p class="card-text"><%= animal.caption %></p>
									    <%= link_to("投稿詳細", animal_path(animal.id), { class: "btn btn-primary" }) %>
									    <div id="animal_<%= animal.id %>">
									    	<%= render 'likes/like', animal: animal %>
									    </div>
									  </div>
									</div>
								</div>
							</div>
						</div>
						<!-- <table style="width:100%">
							<tbody>
								<tr>
									<td>ユーザー名</td>
									<td><%= link_to animal.user.name,user_path(animal.user) %></td>
								</tr>
								<tr>
									<td>動物名</td>
									<td><%= link_to animal.animal_name,animal_path(animal.id) %></td>
								</tr>
								<tr>
									<td><%= attachment_image_tag animal, :image, :fill, 150, 150, format: 'jpeg' %></td>
									<td></td>
								</tr>
								<tr>
									<td>説明</td>
									<td><%= animal.caption %></td>
								</tr>
								<tr>
									<td></td>
									<td><%#= link_to animal_path(animal.user) %></td>
								</tr>
								<tr id="animal_<%= animal.id %>">
							        <%= render 'likes/like', animal: animal %>
							        <td><%#= link_to 'Show', post %></td>
							        <td><%#= link_to 'Edit', edit_post_path(post) %></td>
							        <td><%#= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
								</tr>
							</tbody>
						</table> -->
					</div>
				<% end %>
			</div>
	</div>
</div>
	<div class='col-md-12 back-link'>
		<%= link_to :back do %>
		  <button>戻る</button>
		<% end %>
	</div>
</div>

app/views/animals/new.html.erb
<div class="left">
  <%= form_for(@animal) do |f| %>
    <% if @animal.errors.any? %>
      <%= @animal.errors.count %>件のエラーが発生しました
      <% @animal.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
    <% end %>
  <h1>投稿</h1>

    <h4>動物名</h4>
    <%= f.text_field :animal_name %>

    <h4>画像投稿</h4>
    <%= f.attachment_field :image %>

    <h4>説明</h4>
    <%= f.text_area :caption %>

    <h4></h4>
    <%= f.submit '投稿' %>

    <h4></h4>
    <%= link_to :back do %>
      <button>戻る</button>
    <% end %>
  <% end %>
</div>

app/views/animals/show.html.erb
<div class="container">
		<div class="row">

		<div class="col-xs-3">
			<%= render "users/profile", user: @user %>
		</div>

		<div class="col-xs-9">
			<h2>アニマル詳細</h2>

	    <table class="table">
		  <thead>
		    <tr>
		      <th></th>
		      <th>タイトル</th>
		      <th></th>
		      <th>説明</th>
		    </tr>
		</thead>

	  	<tbody>
		  <tr>
		  	<td><%= attachment_image_tag @user, :profile_image, size: "30x30", fallback: "no_image.jpg" %>
		  		<br>
		  		<%= link_to @animal.user.name,user_path(@animal.user.id) %>
		    </td>

		    <td><%= @animal.animal_name %></td>

		    <td><%= attachment_image_tag @animal, :image, :fill, 150, 150, format: 'jpeg' %></td>

		    <td><%= @animal.caption%></td>
		    <td>
			    <div id="animal_<%= @animal.id %>">
					<%= render 'likes/like', animal: @animal %>
				</div>
			</td>
		  </tr>
		</tbody>
	</table>

	<!-- <div> -->
		<%#= link_to 'delete', [@book,comment], method: :delete %>
	<!-- </div> -->

		<%#= form_for [@book,@comment] do |f| %>
		<%#= f.text_field :body %>
		<%#= f.submit %>
		<% #end %>
  			</div>
		</div>
	</div>
</div>
<%= link_to :back do %>
  <button>戻る</button>
<% end %>

app/views/home/index.html.erb
<div class="container">
<div class="row">
	<div class="top-message col-md-offset-3 col-md-5">
		<div class="text-field">
			<% if flash[:notice] %>
			<p><%= flash[:notice] %></p>
			<% end %>

			<p>
		<h3>welcome to<span class="glyphicon glyphicon-animal" aria-hidden="true"></span>animals!!<br></h3>
	</p>
	<p>
	<h3>
	In <span class="glyphicon glyphicon-animal" aria-hidden="true"></span>animals</h3>
</p>
<p>
	<h5>
	you can share and exchange your opinions , inpressions , and emotions<br>
			about varioius animals!</h5>
		</p>
	</div>

				<div class="row">
					<%= link_to "ログイン", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1 sign_in" %>
				</div>
				<div class="row">
					<%= link_to "新規登録", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1 sign_up" %>
				</div>
			</div>

	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Atsthm</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<body>
  <header>
    <div class="">
      <nav class="navbar navbar-fixed-top navbar-inverse">
          <!-- <div class="collapse navbar-collapse" id="navbarEexample1"> -->
          <ul class="nav navbar-nav list-inline logo">
            <li><h2 class="navbar-brandtitle fab fa-evernote is-4">Atsthm</h2><span class="subtitle" style="Comic Sans MS">Animal that soothes the human mind~人の心を癒す動物</span></li>
          </ul>
        <!--</div> -->
        <ul class="nav">
          <% if user_signed_in? %>
            <li class="nav-item">

              <%= link_to 'ホーム', animals_path, class: "nav-link fas fa-home" %>
            </li>
            <li class="nav-item">
              <%= link_to 'ユーザー一覧', users_path, class: "nav-link fas fa-users" %>
            </li>
            <li class="nav-item">
              <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "nav-link fas fa-sign-out-alt" %>
            </li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>
  <div class="main-container">
    <%= yield %>
  </div>
  <footer>
      <p class="footer-text">© All rights reserved by Infratop.Inc.</p>
  </footer>
</body>
</html>

app/views/likes/_like.html.erb
<% if current_user.liked_by?(animal) %>

		<%= link_to destroy_like_path(animal),class: "like-link", method: :DELETE, remote: true do %> 
		<i class="fa fa-heart unlike-btn"></i>
		<% end %>
		<%= animal.likes.count %>

<% else %>

		<%= link_to create_like_path(animal),class: "like-link", method: :GET, remote: true do %>
		<i class="fa fa-heart like-btn"></i>
		<% end %>
	 	<%= animal.likes.count %>

<% end %>

app/views/likes/create.js.erb
document.getElementById('animal_<%= @animal.id %>').innerHTML = "<%= j(render partial: 'likes/like', locals: { animal: @animal }) %>"

app/views/likes/destroy.js.erb
document.getElementById('animal_<%= @animal.id %>').innerHTML = "<%= j(render partial: 'likes/like', locals: { animal: @animal }) %>"

app/views/relationships/_follow_button.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Unfollow', class: 'btn btn-danger btn-block' %>
    <% end %>
  <% else %>
    <%= form_for(current_user.relationships.build) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Follow', class: 'btn btn-primary btn-block' %>
    <% end %>
  <% end %>
<% end %>

app/views/users/_profile.html.erb
<div id='profile'>
	<h2>ユーザー</h2>
	<%= attachment_image_tag current_user, :profile_image, size: "50x50",format: 'jpg', fallback: "no_image.jpg" %>
	<table class="table profile">

	  <tbody>
		<tr>
			<th>名前</th>
		  	<th><%= current_user.name %></th>
		</tr>
		<tr>
			<th><%= link_to '投稿', new_animal_path, class: "fas fa-plus-square"%></th>
			<th></th>
		</tr>
		<tr>
			<th><%= link_to ' マイページ', users_show_follow_path, class: "fas fa-user" %></th>
			<th></th>
		</tr>

		<tr>
			<th><%= link_to "編集", edit_user_registration_path, class: "fas fa-tools" %></th>
			<th></th>
		</tr>

		<tr>
			<th>follows:<%=  current_user.followings.count %></th>
			<th></th>
		</tr>
		<tr>
			<th>followers:<%= current_user.followers.count %></th>
			<th></th>
		</tr>
	  </tbody>
	</table>
</div>

app/views/users/edit.html.erb
<div class="left">
<h1>編集画面</h1>
<%= form_for(@list, url:"/todolists/#{@list.id}") do |f| %>
  <h4>タイトル</h4>
  <%= f.text_field :title %>
  <h4>本文</h4>
  <%= f.text_area :body %>
  <%= f.submit '保存' %>
<% end %>
</div>

app/views/users/folloer.html.erb
<div style='margin-top: 70px'>
<div class="container">
  <div class="row">
  	<div class="col-xs-9">
      <h2>Follower User</h2>
      <% if @user.followers.blank? %>
		<p>フォローされてません。</p>
        <% else %>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <% @user.followers.each do |user| %>
	<tr>
    <td><%= user.name %></td>
    <td>フォロー数:<%= user.followings.count %></td>
    <td>フォロワー数:<%= user.followers.count %></td>
  <td><%= link_to "Show" ,user_path(user.id) %></td>
  <% end %>
     </table>
     <% end %>
  </div>
</div>
</div>

app/views/users/follow.html.erb
<div style='margin-top: 70px'>
<div class="container">
  <div class="row">
  	<div class="col-xs-9">
      <h2>Follow User</h2>
		<% if @user.followings.blank? %>
		<p>フォローしてません。</p>
        <% else %>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <% @user.followings.each do |user| %>
	<tr>
    <td><%= user.name %></td>
    <td>フォロー数:<%= user.followings.count %></td>
    <td>フォロワー数:<%= user.followers.count %></td>
  <td><%= link_to "Show" ,user_path(user.id) %></td>
  <% end %>
     </table>
       <% end %>
  </div>
</div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
        <%= render "users/profile" %>
    </div>
    <div class="col-xs-9">
      <h2>ユーザー一覧</h2>
<table class="table">
  <thead>
    <tr>
      <th></th>
        <th>ユーザーネーム</th>
        <th></th>
        <th></th>
        <th></th>
        <th colspan="3"></th>
    </tr>
  </thead>
    <% @users.each do |user| %>
      <%= link_to user_path(user) do %>
          <tr>
              <td><%= attachment_image_tag user, :profile_image, size: "50x50",format: 'jpg', fallback: "no_image.jpg" %></td>
              <td><%=link_to user.name, user_path(user) %></td>
              <td>
                <% unless current_user == user %>
                  <% if current_user.following?(user) %>
                    <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
                    <%= hidden_field_tag :follow_id, user.id %>
                    <%= f.submit 'フォロー外す', class: 'btn btn-danger btn-block' %>
                <% end %>
                  <% else %>
                    <%= form_for(current_user.relationships.build) do |f| %>
                      <%= hidden_field_tag :follow_id, user.id %>
                      <%= f.submit 'フォロー', class: 'btn btn-primary btn-block' %>
                    <% end %>
                  <% end %>
              <% end %>
              </td>
          </tr>
      <% end %>
    <% end %>
</table>
    </div>
  </div>
</div>
<%= link_to :back do %>
  <button>戻る</button>
<% end %>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			  <%= render "users/profile" %>
		</div>
		<div class="col-xs-9">
			<h2>ユーザー</h2>
<table class="table">
	<thead>
		<tr>
			<th></th>
		    <th>ユーザーネーム</th>
		    <th>タイトル</th>
		    <th></th>
		    <th>説明</th>
		    <th colspan="3"></th>
		</tr>
	</thead>
		<% @animals.each do |animal| %>
		<tr>
			<td><%= attachment_image_tag @user, :profile_image, size: "30x30", fallback: "no_image.jpg" %></td>
            <td><%= @user.name %></td>
            <td><%= link_to animal.animal_name,animal_path(animal.id) %></td>

		    <td><%= attachment_image_tag animal, :image, :fill, 150, 150, format: 'jpeg' %></td>

		    <td><%= animal.caption%></td>

			<td>
               <% unless current_user.id == animal.user_id %>
                  <% if current_user.following?(@user) %>
                    <%= form_for(current_user.relationships.find_by(follow_id: @user.id), html: { method: :delete }) do |f| %>
                    <%= hidden_field_tag :follow_id, @user.id %>
                    <%= f.submit 'フォロー外す', class: 'btn btn-danger btn-block' %>
                <% end %>
                  <% else %>
                    <%= form_for(current_user.relationships.build) do |f| %>
                      <%= hidden_field_tag :follow_id, @user.id %>
                      <%= f.submit 'フォロー', class: 'btn btn-primary btn-block' %>
                    <% end %>
                  <% end %>
              <% end %>
            </td>
		</tr>
		<% end %>
</table>
		</div>
	</div>
</div>
<%= link_to :back do %>
  <button>戻る</button>
<% end %>

app/views/users/show_follow.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">

      <section class="stats">
        <%#= render 'users/stats' %>
      </section>
        <%= render "users/profile", user: @user %>

    </div>
    <div class="col-xs-9">
      <h2>マイページ</h2>
<table class="table">
  <thead>
    <tr>
      <th></th>
        <th>ユーザーネーム</th>
        <th>タイトル</th>
        <th>説明</th>
        <th></th>
        <th colspan="3"></th>
    </tr>
  </thead>
    <% @animals.each do |animal| %>

    <tr>
      <td><%= attachment_image_tag @user, :profile_image, size: "30x30", fallback: "no_image.jpg" %></td>
            <td><%= @user.name %></td>

        <td><%= attachment_image_tag animal, :image, :fill, 150, 150, format: 'jpeg' %></td>

        <td><%= animal.caption%></td>



        <% if @user == current_user %>
          <td><button type="button" class="btn btn-outline-secondary fas fa-tools"><%= link_to "編集", edit_animal_path(animal.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user" %></button></td>
        <% end %>
        <% if @user == current_user %> 
          <td><button type="button" class="btn btn-outline-danger fas fa-trash-alt"><%= link_to "削除",user_path(animal.id), method: :delete, "data-confirm" => "本当に削除しますか？" %> 
              </button>
            <% end %>
          </td>
    </tr>
    <% end %>

</table>
    </div>
  </div>
</div>
<%= link_to :back do %>
  <button >戻る</button>
<% end %>